name: CI Pipeline (Stage 1 - Compose)

on:
  push:
    branches: [ "testing" ]

env:
  IMAGE_TAG: ${{ github.sha }}    # immutable tag per commit

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # If you keep quick API route tests at repo root:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps & run tests
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pytest -q
          else
            echo "No top-level tests; skipping."
          fi

  build_and_push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx (for better caching/builds)
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build images (compose)
        run: |
          export ACR_LOGIN_SERVER=${{ secrets.ACR_LOGIN_SERVER }}
          export IMAGE_TAG=${{ env.IMAGE_TAG }}
          docker compose -f docker-compose.yml build

      - name: Push images (compose) with SHA tag
        run: |
          export ACR_LOGIN_SERVER=${{ secrets.ACR_LOGIN_SERVER }}
          export IMAGE_TAG=${{ env.IMAGE_TAG }}
          docker compose -f docker-compose.yml push

      - name: Also push :latest tags (optional)
        run: |
          export ACR_LOGIN_SERVER=${{ secrets.ACR_LOGIN_SERVER }}
          # retag and push latest for all three
          docker tag $ACR_LOGIN_SERVER/customer-service:${{ env.IMAGE_TAG }} $ACR_LOGIN_SERVER/customer-service:latest
          docker tag $ACR_LOGIN_SERVER/product-service:${{ env.IMAGE_TAG }}  $ACR_LOGIN_SERVER/product-service:latest
          docker tag $ACR_LOGIN_SERVER/order-service:${{ env.IMAGE_TAG }}    $ACR_LOGIN_SERVER/order-service:latest
          docker push $ACR_LOGIN_SERVER/customer-service:latest
          docker push $ACR_LOGIN_SERVER/product-service:latest
          docker push $ACR_LOGIN_SERVER/order-service:latest
